version: 3.7
services:
  mypostgres:
    image: postgres
    container_name: myposgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "posgres"
      POSTGRES_PASSWORD: "2003"
      POSTGRES_DB: "ticketing-app"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
